# GitHub Actions Workflow: Test Docker Tags
name: "Test Docker Tags"
on:
  workflow_dispatch: # Manuelle Ausführung

env:
  TEST_VERSION: "3.5.19" # Simulierte Version der Anwendung

jobs:
  test-docker-tags:
    name: "Test Docker Tagging"
    runs-on: ubuntu-latest

    steps:
      - name: "Set simulated version"
        id: version
        run: echo "::set-output name=version::${{ env.TEST_VERSION }}"

      - name: "Generate Docker Tags"
        id: generate-tags
        run: |
          # Extrahiere Major, Minor und Patch
          VERSION="${{ steps.version.outputs.version }}"
          MAJOR=$(echo $VERSION | cut -d '.' -f 1)
          MINOR=$(echo $VERSION | cut -d '.' -f 2)
          PATCH=$(echo $VERSION | cut -d '.' -f 3)

          # Docker-Tags simulieren
          echo "Docker Tags:"
          echo "1. latest"
          echo "2. ${VERSION}"
          echo "3. ${MAJOR}"
          echo "4. ${MAJOR}.${MINOR}"
          
          # Ergebnisse für nachfolgende Schritte
          echo "::set-output name=tags::latest,${VERSION},${MAJOR},${MAJOR}.${MINOR}"

      - name: "Verify Tags"
        run: |
          echo "Generated tags:"
          echo "${{ steps.generate-tags.outputs.tags }}"
